# Netlify Configuration for HLSitech Dashboard
# Next.js 15 with @netlify/plugin-nextjs

[build]
  command = "npm run build"
  # DO NOT set publish - the Next.js plugin handles deployment

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "22"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"
    Content-Security-Policy = "frame-ancestors 'self'"
    X-Robots-Tag = "noindex, nofollow"
